excerpt_separator: ""
pygments: true
markdown: kramdown
url: http://jiunwu.github.io
title: 10115 Berlin
tagline: ideas came from Berlin
description: About Mobile App, High-Tech Startup, Marketplaces, SaaS, FinTech
paginate: 10
