excerpt_separator: ""
pygments: true
markdown: kramdown
url: http://jiunwu.github.io
title: Prototype
tagline: thinking in cloud
description: About Mobile App, High-Tech Startup, Marketplaces, SaaS, Payment
paginate: 10
