excerpt_separator: ""
pygments: true
markdown: KramdownPygments
url: http://jiunwu.github.io
title: Jiun Wu
tagline: Berlin
description: About Mobile App, High-Tech Startup, Marketplaces, SaaS, Payment
paginate: 10
email: jiun.wu@icloud.com
